# This file was generated by GoReleaser. DO NOT EDIT.
cask "switchtender" do
  version "1.49.0"

  on_macos do
    sha256 "16aacd0327f59ce82c09388dfab247c600144b11900ccf0658300a1e09f962ee"
    url "https://github.com/kordloom/switchtender/releases/download/v#{version}/switchtender_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "ca82c1437ed3d5bfcc240c615306c5b1a3b52a67391e9d446702544caee5cbe3"
      url "https://github.com/kordloom/switchtender/releases/download/v#{version}/switchtender_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1d237be8d164df583ffbef1a6473eeea2d1ef05370480eff3bb8817518a5d329"
      url "https://github.com/kordloom/switchtender/releases/download/v#{version}/switchtender_#{version}_linux_arm64.tar.gz"
    end
  end

  name "switchtender"
  desc "Run everything, watch every host, prove every change: one binary control plane for Ansible, Terraform, OpenTofu, Bash, PowerShell, Python, and Go."
  homepage "https://switchtender.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "switchtender"

  # No zap stanza required

end
