# This file was generated by GoReleaser. DO NOT EDIT.
cask "switchtender" do
  version "1.36.1"

  on_macos do
    sha256 "14632353c0c62ec98be9380dae1ae376aa82987bff28947405466d97e12df0f6"
    url "https://github.com/kordloom/switchtender/releases/download/v#{version}/switchtender_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "b672706f5bd65cba39f6ed30f93ded7ee0da5416d95ac2afb49722650d587226"
      url "https://github.com/kordloom/switchtender/releases/download/v#{version}/switchtender_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "15bd1cc73cb421213c3c109f6f09c29c4f5392b9c1c7318ebc40b7fa34516a43"
      url "https://github.com/kordloom/switchtender/releases/download/v#{version}/switchtender_#{version}_linux_arm64.tar.gz"
    end
  end

  name "switchtender"
  desc "Run everything, watch every host, prove every change: one binary control plane for Ansible, Terraform, OpenTofu, Bash, PowerShell, Python, and Go."
  homepage "https://switchtender.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "switchtender"

  # No zap stanza required

end
