# This file was generated by GoReleaser. DO NOT EDIT.
cask "switchtender" do
  version "1.101.0"

  on_macos do
    sha256 "c858ff5953927b37d50541929d603a9774c4016441358ad1f96b290c71ae473a"
    url "https://github.com/kordloom/switchtender/releases/download/v#{version}/switchtender_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "2340ef46d0be408e4a2418ea3c905b2de02cf053c7033a9d322dd47e21923957"
      url "https://github.com/kordloom/switchtender/releases/download/v#{version}/switchtender_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8dcb0a9480fd0e4db0a8595a24f88922de47bcb298b0601e1cba38afba1d7b73"
      url "https://github.com/kordloom/switchtender/releases/download/v#{version}/switchtender_#{version}_linux_arm64.tar.gz"
    end
  end

  name "switchtender"
  desc "One control point for every way your infrastructure can change"
  homepage "https://switchtender.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "switchtender"

  # No zap stanza required

end
