# This file was generated by GoReleaser. DO NOT EDIT.
cask "whodar" do
  version "0.48.0"

  on_macos do
    on_arm do
      sha256 "e1e97c1cc3fc1ec3011c5b981914175caa9f9011b20e4dc9e000559953090909"
      url "https://github.com/kordloom/whodar/releases/download/v#{version}/whodar_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6bd5ddd216b37c849410b2f3d3f1a6a76d2977ae7cbf0707c0a5b83e9b4e67f2"
      url "https://github.com/kordloom/whodar/releases/download/v#{version}/whodar_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bda5951e256fc0e868e6c8f3984c31d0319bca6ee16dfdd93fd38d33820a0b60"
      url "https://github.com/kordloom/whodar/releases/download/v#{version}/whodar_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bf4de01980d4c4089d2c76b39ac728430eb6f718430565dcdaebda6bb35cd12e"
      url "https://github.com/kordloom/whodar/releases/download/v#{version}/whodar_#{version}_linux_amd64.tar.gz"
    end
  end

  name "whodar"
  desc "Know who knows. Find who to talk to about X across your work tools."
  homepage "https://whodar.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "whodar"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/whodar"]
    end
  end

  # No zap stanza required
end
