# This file was generated by GoReleaser. DO NOT EDIT.
cask "whodar" do
  version "0.38.0"

  on_macos do
    on_intel do
      sha256 "f7d675fa813263fc02d8e933d5b2f70dd0dfee82a89c3eee963d787bc809f108"
      url "https://github.com/kordloom/whodar/releases/download/v#{version}/whodar_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "65a0642ac73772a4bf7435470aa0a3027fbbb127a9e1be7b0faff32c410e2f4e"
      url "https://github.com/kordloom/whodar/releases/download/v#{version}/whodar_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2196bcc36f276aa25d436ae97dc1442760b96577cae24fcd6cbea52bc85899f3"
      url "https://github.com/kordloom/whodar/releases/download/v#{version}/whodar_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "160eda93d2df462c1f07a618a0ef71238680d3ea863fc28e781d4764173901f4"
      url "https://github.com/kordloom/whodar/releases/download/v#{version}/whodar_#{version}_linux_arm64.tar.gz"
    end
  end

  name "whodar"
  desc "Know who knows. Find who to talk to about X across your work tools."
  homepage "https://whodar.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "whodar"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/whodar"]
    end
  end

  # No zap stanza required

end
