# This file was generated by GoReleaser. DO NOT EDIT.
cask "whodar" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "d303ecc75126903054c0150e942c2a589e8bb148064ab50cd551e5a79e0ce683"
      url "https://github.com/kordloom/whodar/releases/download/v#{version}/whodar_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b6134a36004934137b68a1e1ee7afc2e14a614a1c4450a89995335c07c5a4681"
      url "https://github.com/kordloom/whodar/releases/download/v#{version}/whodar_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ddf10f0fd98ba1ff70e7834a78145a6cea9db6e8c741d1e7d8aae4e86c439351"
      url "https://github.com/kordloom/whodar/releases/download/v#{version}/whodar_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4c1d0dbb3bcc6c0a857ef578056ea60beb0a526def6425bb9744fc62f18924d8"
      url "https://github.com/kordloom/whodar/releases/download/v#{version}/whodar_#{version}_linux_arm64.tar.gz"
    end
  end

  name "whodar"
  desc "Know who knows. Find who to talk to about X across your work tools."
  homepage "https://whodar.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "whodar"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/whodar"]
    end
  end

  # No zap stanza required

end
